version: 2.0
jobs:
  build:
    working_directory: ~/rangle/treillage
    shell: /bin/bash --login
    docker:
      - image: node:8.11.3
    steps:
      - checkout
      - run:
          name: "Installing Node & Yarn"
          command: |
            nvm install 8.11.3 && nvm alias default 8.11.3
            npm install -g yarn@1.7.0
      - restore_cache:
          name: "Restore Yarn Package Cache"
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: "Installing Dependencies"
          command:  |
            yarn install
      - run:
          name: "Linting & Tests"
          command: |
            yarn run lint
            yarn run test
      - run:
          name: "Building & Deploying"
          command: |
            yarn run build
            ./scripts/deploy-ghpages.sh dist
